systems/admin         /usr/share/fusiondirectory/plugins
systems/personal      /usr/share/fusiondirectory/plugins
systems/addons        /usr/share/fusiondirectory/plugins
systems/locale        /usr/share/fusiondirectory/locale/plugins/systems
systems/html/images   /usr/share/fusiondirectory/html/plugins/systems
systems/contrib/encodings        /var/cache/fusiondirectory/systems
systems/contrib/resolutions      /var/cache/fusiondirectory/systems

