coreplugins/goto/admin        /usr/share/fusiondirectory/plugins
coreplugins/goto/personal     /usr/share/fusiondirectory/plugins
coreplugins/goto/addons       /usr/share/fusiondirectory/plugins
coreplugins/goto/locale       /usr/share/fusiondirectory/locale/plugins/goto
coreplugins/goto/contrib      /usr/share/doc/fusiondirectory-plugin-goto
coreplugins/goto/html/images  /usr/share/fusiondirectory/html/plugins/goto
