plugins-extra/asterisk/admin                            /usr/share/fusiondirectory/plugins
plugins-extra/asterisk/addons                           /usr/share/fusiondirectory/plugins
plugins-extra/asterisk/config                           /usr/share/fusiondirectory/plugins
plugins-extra/asterisk/personal                         /usr/share/fusiondirectory/plugins
plugins-extra/asterisk/locale                           /usr/share/fusiondirectory/locale/plugins/asterisk
plugins-extra/asterisk/html/images                      /usr/share/fusiondirectory/html/plugins/asterisk
