gofax/admin             /usr/share/fusiondirectory/plugins
gofax/addons            /usr/share/fusiondirectory/plugins
gofax/personal          /usr/share/fusiondirectory/plugins
gofax/locale            /usr/share/fusiondirectory/locale/plugins/gofax
gofax/contrib           /usr/share/doc/fusiondirectory-plugin-gofax
gofax/html/getfax.php   /usr/share/fusiondirectory/html/plugins/gofax
gofax/html/images       /usr/share/fusiondirectory/html/plugins/gofax
