plugins/supann/contrib/supann  /etc/fusiondirectory
plugins/supann/admin           /usr/share/fusiondirectory/plugins
plugins/supann/config          /usr/share/fusiondirectory/plugins
plugins/supann/personal        /usr/share/fusiondirectory/plugins
plugins/supann/locale          /usr/share/fusiondirectory/locale/plugins/supann
plugins/supann/html/images     /usr/share/fusiondirectory/html/plugins/supann


