asterisk/admin                            /usr/share/fusiondirectory/plugins
asterisk/addons                           /usr/share/fusiondirectory/plugins
asterisk/config                           /usr/share/fusiondirectory/plugins
asterisk/personal                         /usr/share/fusiondirectory/plugins
asterisk/locale                           /usr/share/fusiondirectory/locale/plugins/asterisk
asterisk/html/images                      /usr/share/fusiondirectory/html/plugins/asterisk
