plugins-extra/systems/contrib/openldap/mime-fd.schema               /etc/ldap/schema/fusiondirectory
plugins-extra/systems/contrib/openldap/service-fd.schema            /etc/ldap/schema/fusiondirectory
plugins-extra/systems/contrib/openldap/systems-fd.schema            /etc/ldap/schema/fusiondirectory
plugins-extra/systems/contrib/openldap/systems-fd-conf.schema       /etc/ldap/schema/fusiondirectory

