plugins-extra/supann/contrib/supann/activite_CNU                /etc/fusiondirectory/supann/
plugins-extra/supann/contrib/supann/activite_REFERENS           /etc/fusiondirectory/supann/
plugins-extra/supann/contrib/supann/diplome_SISE                /etc/fusiondirectory/supann/
plugins-extra/supann/contrib/supann/discipline_SISE             /etc/fusiondirectory/supann/
plugins-extra/supann/contrib/supann/etablissement_SUPANN        /etc/fusiondirectory/supann/
plugins-extra/supann/contrib/supann/eturegimeinscription_SISE   /etc/fusiondirectory/supann/
plugins-extra/supann/contrib/supann/typediplome_SISE            /etc/fusiondirectory/supann/
plugins-extra/supann/contrib/supann/affiliation                 /etc/fusiondirectory/supann/
plugins-extra/supann/contrib/supann/corps                       /etc/fusiondirectory/supann/
plugins-extra/supann/contrib/supann/entite                      /etc/fusiondirectory/supann/
plugins-extra/supann/contrib/supann/role                        /etc/fusiondirectory/supann/
plugins-extra/supann/contrib/supann/diplome_EXAMPLE                 /usr/share/doc/fusiondirectory/example
plugins-extra/supann/contrib/supann/discipline_EXAMPLE              /usr/share/doc/fusiondirectory/example
plugins-extra/supann/contrib/supann/etuelementpedagogique_EXAMPLE   /usr/share/doc/fusiondirectory/example
plugins-extra/supann/contrib/supann/etuetape_EXAMPLE                /usr/share/doc/fusiondirectory/example
plugins-extra/supann/contrib/supann/eturegimeinscription_EXAMPLE    /usr/share/doc/fusiondirectory/example
plugins-extra/supann/contrib/supann/typediplome_EXAMPLE             /usr/share/doc/fusiondirectory/example
plugins-extra/supann/admin           /usr/share/fusiondirectory/plugins
plugins-extra/supann/config          /usr/share/fusiondirectory/plugins
plugins-extra/supann/personal        /usr/share/fusiondirectory/plugins
plugins-extra/supann/locale          /usr/share/fusiondirectory/locale/plugins/supann
plugins-extra/supann/html/images     /usr/share/fusiondirectory/html/plugins/supann


