argonaut-fai-server/bin/ldap2fai                                usr/sbin
argonaut-fai-server/lib/get-config-dir-argonaut                 usr/lib/fai
argonaut-fai-server/nfsroot-hooks/argonaut-nfsroot-integration  etc/fai/nfsroot-hooks
argonaut-fai-server/nfsroot-templates/initramfs.conf            etc/fai/nfsroot-templates
argonaut-fai-server/nfsroot-templates/update-initramfs.conf     etc/fai/nfsroot-templates
argonaut-fai-server/nfsroot-templates/usplash.conf              etc/fai/nfsroot-templates

