plugins/systems/admin                   /usr/share/fusiondirectory/plugins
plugins/systems/config                  /usr/share/fusiondirectory/plugins
plugins/systems/addons/dashboard		/usr/share/fusiondirectory/plugins/addons/dashboard
plugins/systems/locale                  /usr/share/fusiondirectory/locale/plugins/systems
plugins/systems/html/images             /usr/share/fusiondirectory/html/plugins/systems

