plugins-extra/ppolicy/addons                  /usr/share/fusiondirectory/plugins
plugins-extra/ppolicy/admin                   /usr/share/fusiondirectory/plugins
plugins-extra/ppolicy/config                  /usr/share/fusiondirectory/plugins
plugins-extra/ppolicy/personal                /usr/share/fusiondirectory/plugins
plugins-extra/ppolicy/locale                  /usr/share/fusiondirectory/locale/plugins/ppolicy
plugins-extra/ppolicy/html/themes             /usr/share/fusiondirectory/html


