plugins/ppolicy/contrib/openldap/ppolicy-fd-conf.schema         /etc/ldap/schema/fusiondirectory
plugins/ppolicy/contrib/openldap/ppolicyconfig.ldif             /usr/share/doc/fusiondirectory-plugin-ppolicy
plugins/ppolicy/contrib/openldap/ppolicydefault.ldif            /usr/share/doc/fusiondirectory-plugin-ppolicy
plugins/ppolicy/contrib/openldap/ppolicymodule.ldif             /usr/share/doc/fusiondirectory-plugin-ppolicy
